apiVersion: v1
kind: Service
metadata:
  name: callout
  namespace: callout
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "callout"},"443":{"name": "callout-https"}}}'
spec:
  selector:
    app: callout
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: callout
  - protocol: TCP
    port: 443
    targetPort: 443
    name: callout-https
  type: LoadBalancer
