apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: echo-server
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "echo-server"}}}'
spec:
  selector:
    app: echo-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
